name: CI Build
on:
  push:
    branches:
      - snapshot
      - main
  pull_request:
    branches:
      - snapshot
      - main

env:
  LC_ALL: en_US.UTF-8
  GRADLE_OPTS: >-
    -Dorg.gradle.parallel=true

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CS_PASSWORD: ${{secrets.CENTRAL_SONATYPE_TOKEN_PASSWORD}}
      CS_USERNAME: ${{secrets.CENTRAL_SONATYPE_TOKEN_USERNAME}}
      GPG_PASSPHRASE: ${{secrets.GPG_PASSPHRASE}}
      GPG_KEY_ID: ${{secrets.GPG_KEY_ID}}
      GPG_PRIVATE_KEY: ${{secrets.GPG_PRIVATE_KEY}}
      DO_RELEASE: ${{ github.ref == 'refs/heads/main' && 'true' || 'false' }}
    steps:
    - name: Git Checkout
      uses: actions/checkout@v4
    - name: Create Staging Repository
      if: ${{ (github.ref == 'refs/heads/main') }}
      run: |
        ./.github/scripts/stage.sh org.eclipse.fennec
